name: teleicu-monitoring-system

channels:
  - pytorch  
  - conda-forge  

dependencies:
  - python==3.11
  
  - pip:
    - torch
    - pytorch=2.0.1
    - torchvision=0.15.2
    - onnx=1.14.0
    - onnxruntime=1.15.1
    - pycocotools=2.0.7
    - pyyaml=6.0.1
    - scipy=1.13.0
    - onnxsim=0.4.36
    - opencv-python=4.9.0.80
    - psutil=5.9.8
    - py-cpuinfo=9.0.0
    - huggingface-hub=0.23.2
    - safetensors=0.4.3
    - pyqt=5.15.1
    - supervision=0.21.0
    - deep-sort-realtime=1.3.2
    - flask=3.0.3
